const territories=[['quiet','01','Quiet / Focus','Il vuoto riduce la competizione fra elementi e rende importante ciò che rimane.'],['typographic','02','Bold / Typographic','Dimensione, peso, contrasto e interruzioni di riga danno una forma all’intenzione.'],['immersive','03','Immersive / Transformation','La differenza fra scegliere qualcosa ed essere già dentro quell’esperienza.'],['ritual','04','Ritual / Emotional','Dare significato alla scelta, alla conclusione e a ciò che resta nel tempo.']];
const escapeHTML=s=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
document.getElementById('gallery').innerHTML=territories.map(([key,num,title,desc])=>`<section class="territory" id="${key}"><div class="territory-head"><div><p class="eyebrow">TERRITORIO ${num}</p><h2>${title}</h2></div><p>${desc}</p></div><div class="grid">${references.filter(r=>r.territory===key).map(r=>`<article class="reference ${[1,13,18].includes(r.id)?'flow':''}" id="ref-${r.id}"><div class="image-well">${([1,13,18].includes(r.id)?Array.from({length:({1:4,13:3,18:2})[r.id]},(_,i)=>`${r.id}-${i+1}.png`):[`${r.id}.${r.id===3?'webp':'png'}`]).map((file,i)=>`<figure><button class="shot" data-image="images/${file}" data-label="${escapeHTML(r.app+' — '+r.title)}" aria-label="Ingrandisci ${escapeHTML(r.app)}${[1,13,18].includes(r.id)?' — passaggio '+(i+1):''}"><img src="images/${file}" alt="${escapeHTML(r.app+' — '+r.title)}${[1,13,18].includes(r.id)?' — passaggio '+(i+1):''}" loading="lazy" decoding="async"></button>${[1,13,18].includes(r.id)?`<figcaption>0${i+1} — ${({1:['Prima','Scrittura','Conferma','Dopo'],13:['Prima','Scelta del suono','Selezione attiva'],18:['Attività','Focus']})[r.id][i]}</figcaption>`:''}</figure>`).join('')}</div><div class="ref-meta"><span>${String(r.id).padStart(2,'0')} / ${key.toUpperCase()}</span>${r.finalist?'<span class="tag">★ SELEZIONE FINALE</span>':''}</div><h3>${escapeHTML(r.app)}</h3><p class="screen-title">${escapeHTML(r.title)}</p><p class="why">${escapeHTML(r.why)}</p><p class="steal"><b>Cosa prendere</b>${escapeHTML(r.steal)}</p><a class="source" href="${r.url}" target="_blank" rel="noopener noreferrer">${r.url.includes('/flows/')?'Apri il flusso':'Apri la schermata'} su Mobbin ↗</a></article>`).join('')}</div></section>`).join('');
const interpretations=['Un’intenzione rimane da sola dopo che l’interfaccia ha svolto il proprio compito.','Le parole diventano una composizione: dimensione, contrasto e righe esprimono il peso della scelta.','Scegliere significa entrare in uno stato diverso attraverso riduzione, ambiente o geometria.','La scelta nasce dal linguaggio personale e lascia una traccia visiva nel tempo.'];
document.getElementById('finalists').innerHTML=territories.map(([key,num,title],i)=>`<div class="final-row"><h3>${num} — ${title.split(' / ')[0]}</h3><div class="names">${references.filter(r=>r.territory===key&&r.finalist).map(r=>`<a href="#ref-${r.id}">${escapeHTML(r.app)}</a>`).join('<span>·</span>')}</div><p>${interpretations[i]}</p></div>`).join('');

const viewer=document.createElement('dialog');viewer.className='viewer';viewer.innerHTML='<button class="close-viewer" aria-label="Chiudi immagine">×</button><img alt=""><p></p>';document.body.append(viewer);
let opener;
document.querySelectorAll('.shot').forEach(button=>button.addEventListener('click',()=>{opener=button;viewer.querySelector('img').src=button.dataset.image;viewer.querySelector('img').alt=button.dataset.label;viewer.querySelector('p').textContent=button.dataset.label;viewer.showModal();}));
viewer.querySelector('button').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});viewer.addEventListener('close',()=>opener?.focus());
